baseURL = "http://example.org/"
languageCode = "en-ru"
title = "Typical Cat Lover"
theme = "Ananke"



[params]
featured_image = "/images/cat.jpg"
background_color_class = "bg-light-pink"
site_logo = "/images/logo-192x192.png"
favicon = "/images/favicon.png"
